#!/bin/bash
chmod u+x,g+x,0+r hello
#!/bin/bash
chmod u+x,g+x,0+r hello
#!/bin/bash
chmod u+x,g+x,0+r hello
#!/bin/bash
chmod u+x,g+x,0+r hello
#!/bin/bash
chmod u+x,g+x,0+r hello
#!/bin/bash
chmod u+x,g+x,0+r hello



